# Generated by Django 4.1.3 on 2024-08-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=55)),
                ('userName', models.CharField(max_length=55)),
                ('rating', models.IntegerField()),
                ('client', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
    ]
