# Generated by Django 4.1.3 on 2024-08-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pay', models.CharField(max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('acceptedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_jobs', to='influencedapi.user')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencedapi.user')),
            ],
        ),
    ]
