# Generated by Django 4.1.3 on 2024-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0005_alter_application_unique_together_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
