# Generated by Django 4.1.3 on 2024-11-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0005_rename_client_job_client_id'),
        ('influencedapi', '0006_application_message'),
    ]

    operations = [
    ]
