# Generated by Django 4.1.3 on 2024-11-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0007_merge_20241128_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
