# Generated by Django 4.1.3 on 2024-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0008_remove_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
