# Generated by Django 4.1.3 on 2024-12-02 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0009_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hasApplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='acceptedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_jobs', to='influencedapi.user'),
        ),
    ]
