# Generated by Django 4.1.3 on 2024-12-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0011_user_socials_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='socials',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='influencedapi.social'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, null=True, unique=True),
        ),
    ]
