# Generated by Django 4.1.3 on 2024-12-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0012_remove_social_user_remove_user_socials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
    ]
