# Generated by Django 4.1.3 on 2024-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0013_rename_username_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(default='default_username', max_length=55, unique=True),
        ),
    ]
