# Generated by Django 4.1.3 on 2024-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0018_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
    ]
