# Generated by Django 4.1.3 on 2024-12-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0022_remove_user_social_alter_social_id_alter_social_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.AddField(
            model_name='social',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='social', to='influencedapi.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='socials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='influencedapi.social'),
            preserve_default=False,
        ),
    ]
