# Generated by Django 4.1.3 on 2024-12-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0023_remove_social_user_social_user_id_user_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='influencedapi.user'),
        ),
    ]
