# Generated by Django 4.1.3 on 2024-12-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencedapi', '0024_alter_social_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='influencedapi.user'),
        ),
    ]
